# Generated by Django 5.0.6 on 2024-05-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='justification',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
