# Generated by Django 5.0.6 on 2024-06-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0005_alter_etudiant_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='justification',
            field=models.FileField(blank=True, null=True, upload_to='justifie'),
        ),
    ]
