# Generated by Django 5.0.6 on 2024-06-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0006_alter_absence_justification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='justification',
            field=models.FileField(blank=True, null=True, upload_to='photos'),
        ),
    ]
